services:
  db:
    image: postgres:16
    container_name: javaDB
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: javadatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: java_project
    build: .
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/javadatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - db
volumes:
  db_data: